// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXUiXLH9CZMRqIVscMXXQEqssg9ttV0Ts',
    appId: '1:311846868311:web:048ef95c8bacd216e9da12',
    messagingSenderId: '311846868311',
    projectId: 'scanproducts-c672f',
    authDomain: 'scanproducts-c672f.firebaseapp.com',
    storageBucket: 'scanproducts-c672f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjD5BhpX7QXGi2kdz0iLLfcNY4hTUU6hc',
    appId: '1:311846868311:android:903739fa4211151ae9da12',
    messagingSenderId: '311846868311',
    projectId: 'scanproducts-c672f',
    storageBucket: 'scanproducts-c672f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZvqGns79j08OMkVBcjOzmU0cITski4CQ',
    appId: '1:311846868311:ios:6c7a1adf87cc16fde9da12',
    messagingSenderId: '311846868311',
    projectId: 'scanproducts-c672f',
    storageBucket: 'scanproducts-c672f.appspot.com',
    iosBundleId: 'com.example.scanProductsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZvqGns79j08OMkVBcjOzmU0cITski4CQ',
    appId: '1:311846868311:ios:6c7a1adf87cc16fde9da12',
    messagingSenderId: '311846868311',
    projectId: 'scanproducts-c672f',
    storageBucket: 'scanproducts-c672f.appspot.com',
    iosBundleId: 'com.example.scanProductsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXUiXLH9CZMRqIVscMXXQEqssg9ttV0Ts',
    appId: '1:311846868311:web:283a79dbe609c6d2e9da12',
    messagingSenderId: '311846868311',
    projectId: 'scanproducts-c672f',
    authDomain: 'scanproducts-c672f.firebaseapp.com',
    storageBucket: 'scanproducts-c672f.appspot.com',
  );
}
